server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /P7-platform
############################################################
#
# 配置数据源信息
#
############################################################
#数据源配置
spring:
  datasource:
    #postgresql配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://140.143.18.246:3306/p7-platform?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: Songjiang_0702

    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化连接池、最小值、最大值
    initialSize: 5
    minIdle: 10
    maxActive: 30
    #配置获取连接等待超时的时间，单位是毫秒
    maxWait: 10000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: config,stat,slf4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  thymeleaf:
    cache: false  #缓存是否开启
    encoding: UTF-8 #编码格式
    mode: LEGACYHTML5 #去除对html的严格校验
    suffix: .html
    prefix: classpath:/templates/

    messages:
      basename: i18n
      encoding: UTF-8

    resources:
      static-locations: classpath:/static/
#  data:
#    #jackson
#    jackson:
#      deserialization:
#        #@RequestBody中是否允许不存在的属性
#        fail-on-unknown-properties: true
#      default-property-inclusion: NON_NULL

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.song.p7.platform.pojo # 所有POJO类所在包路径
  configuration:
    lazy-load-trigger-methods:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml # mapper映射文件

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# SWAGGER UI
swagger-ui:
  enabled: true